# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://umr-ds.github.io"
baseurl: "/seamcon"

# Name of website
title: Seamless Handovers

# Short description of your site
description: Learning Wi-Fi Connection Loss Predictions for Seamless Vertical Handovers Using Multipath TCP

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: index
  Guides:
    - Android 4.4.2: stock_android
    - MPTCP Kernel: mptcp_kernel
    - Video Stream: video_stream
    - Apps: install_apps
  ML Details: ml
  Downloads: downloads

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/seamcon-logo-notext.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: ""

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Distributed Systems Group, University of Marburg

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  email: "hoechst@mathematik.uni-marburg.de"
  github: "umr-ds"

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - commons
  - learners
  - seamless
  - "*.ipynb"
theme: jekyll-theme-slate